# -*- coding: utf-8 -*-
"""Draw the VoiceittBridge application icon.

Kept as code rather than a binary nobody can edit: the icon is regenerated by
running this, and the design decisions are the comments below.

The mark is a bridge arch with a voice waveform passing under it -- the app
carries speech across to whatever window the user is typing into. Colours are
the HUD's own (Hud.cs): near-black ground, cyan structure, and the single red
accent this app uses for "live".

Legibility at 16 px drove every choice: three bars rather than five, one thick
arch rather than a drawn span, no text, and a rim light so the shape survives on
both the dark taskbar and a light Explorer window.

    python tools/make_icon.py          # writes app.ico and tools/icon-preview.png
"""

from __future__ import annotations

import sys
from pathlib import Path

from PIL import Image, ImageDraw

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent

GROUND = (4, 8, 15, 255)        # Hud.Ground
CYAN = (86, 217, 255, 255)      # Hud.Cyan
RED = (255, 42, 42, 255)        # Hud.Red
RIM = (22, 48, 74, 255)         # Hud.Line

SIZES = [256, 128, 64, 48, 32, 24, 16]
S = 1024                        # draw large, downsample for clean edges


def draw_icon(detailed: bool = True) -> Image.Image:
    """The mark. `detailed` adds the waveform, which is noise below ~32 px."""
    img = Image.new("RGBA", (S, S), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)

    # Ground: a rounded square, not a circle -- it reads as an app tile on the
    # taskbar and keeps more area for the mark at small sizes.
    pad = int(S * 0.04)
    d.rounded_rectangle([pad, pad, S - pad, S - pad], radius=int(S * 0.22),
                        fill=GROUND, outline=RIM, width=int(S * 0.02))

    # A suspension bridge, drawn the way the eye recognizes one: two towers, a
    # cable dipping between them, a deck running across. The first attempt used
    # a single arch over three bars and read as headphones -- the towers are
    # what make it unmistakably a bridge.
    deck_y = int(S * 0.64)
    tower_top = int(S * 0.24)
    tower_x = [int(S * 0.31), int(S * 0.69)]
    stroke = int(S * 0.062)

    # Cable: a parabola sagging from tower top to tower top.
    sag = int(S * 0.17)
    pts = []
    for i in range(41):
        t = i / 40
        x = tower_x[0] + (tower_x[1] - tower_x[0]) * t
        y = tower_top + sag * (1 - (2 * t - 1) ** 2)
        pts.append((x, y))
    # Side cables, sweeping down to the deck at the outer edges.
    edge_l, edge_r = int(S * 0.14), int(S * 0.86)
    d.line([(edge_l, deck_y - int(S * 0.02)), (tower_x[0], tower_top)],
           fill=CYAN, width=int(stroke * 0.55))
    d.line([(tower_x[1], tower_top), (edge_r, deck_y - int(S * 0.02))],
           fill=CYAN, width=int(stroke * 0.55))
    d.line(pts, fill=CYAN, width=int(stroke * 0.7), joint="curve")

    # Towers.
    for x in tower_x:
        d.rounded_rectangle([x - stroke // 2, tower_top - int(S * 0.03),
                             x + stroke // 2, deck_y],
                            radius=stroke // 2, fill=CYAN)

    # Deck: the widest element, so the silhouette has a base at any size.
    d.rounded_rectangle([edge_l, deck_y, edge_r, deck_y + int(S * 0.062)],
                        radius=int(S * 0.031), fill=CYAN)

    if not detailed:
        # Small sizes: one red mark under the deck instead of three bars. At
        # 16 px three bars merge into a smudge, and a smudge is worse than
        # nothing -- the bridge alone still identifies the app.
        r = int(S * 0.055)
        cx, cy = S // 2, int(S * 0.80)
        d.rounded_rectangle([cx - r, cy - int(r * 1.5), cx + r, cy + int(r * 1.5)],
                            radius=r, fill=RED)
        return img

    # What crosses the bridge: a voice. Three bars below the deck, the middle
    # one red -- this app's one accent colour, used for "live" everywhere else.
    bar_w = int(S * 0.062)
    gap = int(S * 0.055)
    heights = [0.085, 0.145, 0.085]
    colours = [CYAN, RED, CYAN]
    total = 3 * bar_w + 2 * gap
    x = (S - total) // 2
    mid = int(S * 0.815)
    for h, colour in zip(heights, colours):
        half = int(S * h / 2)
        d.rounded_rectangle([x, mid - half, x + bar_w, mid + half],
                            radius=bar_w // 2, fill=colour)
        x += bar_w + gap
    return img


#: Below this, the waveform is dropped (see draw_icon).
DETAIL_FLOOR = 32


def render(size: int, detailed_master: Image.Image,
           simple_master: Image.Image) -> Image.Image:
    master = detailed_master if size >= DETAIL_FLOOR else simple_master
    return master.resize((size, size), Image.LANCZOS)


def main() -> int:
    detailed = draw_icon(True)
    simple = draw_icon(False)
    frames = [render(n, detailed, simple) for n in SIZES]

    ico = ROOT / "app.ico"
    frames[0].save(ico, format="ICO", sizes=[(n, n) for n in SIZES],
                   append_images=frames[1:])
    print(f"wrote {ico.relative_to(ROOT)} ({', '.join(str(n) for n in SIZES)}; "
          f"waveform dropped below {DETAIL_FLOOR} px)")
    master = detailed

    # A preview sheet, so the design can be judged at the size it will be seen.
    strip_sizes = [128, 64, 48, 32, 16]
    pad = 16
    width = sum(strip_sizes) + pad * (len(strip_sizes) + 1)
    height = max(strip_sizes) + pad * 2
    sheet = Image.new("RGBA", (width, height), (245, 245, 245, 255))
    x = pad
    for n in strip_sizes:
        frame = render(n, detailed, simple)
        sheet.paste(frame, (x, (height - n) // 2), frame)
        x += n + pad
    preview = HERE / "icon-preview.png"
    sheet.save(preview)
    print(f"wrote {preview.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
